[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'context_filetype.vim']
on_event = ['InsertEnter']
hook_source = '''
  inoremap <silent><expr> <C-l> ddc#complete_common_string()
  inoremap <silent><expr> <CR>  pumvisible() ? "\<C-y>" : "\<CR>"
  ""inoremap <silent><expr> <TAB> ddc#map#manual_complete()
  inoremap <expr> <TAB>
        \ pum#visible() ?
        \   '<Cmd>call pum#map#insert_relative(+1, "empty")<CR>' :
        \ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
        \   '<TAB>' : ddc#map#manual_complete()
  inoremap <C-n>   <Cmd>call pum#map#select_relative(+1)<CR>
  inoremap <C-p>   <Cmd>call pum#map#select_relative(-1)<CR>
  ""inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1, "empty")<CR>
  ""inoremap <C-p>   <Cmd>call pum#map#insert_relative(-1, "empty")<CR>
  inoremap <C-y>   <Cmd>call pum#map#confirm()<CR>
  inoremap <C-o>   <Cmd>call pum#map#confirm_word()<CR>

  call ddc#custom#patch_global('sources', ['vim-lsp', 'around', 'buffer', 'file'])
  call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'ignoreCase': v:true,
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \ },
      \ 'around': {
      \     'mark': 'A',
      \  },
      \ 'buffer': {
      \     'mark': 'B',
      \  },
      \ 'file': {
      \     'mark': 'F',
      \     'isVolatile': v:true,
      \     'forceCompletionPattern': '\S/\S*',
      \     'minAutoCompleteLength': 1,
      \  },
      \ 'vim-lsp': {
      \     'mark': 'LSP',
      \     'forceCompletionPattern': '\.\w*|:\w*|->\w*',
      \     'minAutoCompleteLength': 1,
      \ },
      \ })
  call ddc#custom#patch_global('sourceParams', {
      \ 'buffer': {
      \    'requireSameFiletype': v:false
      \ },
      \ })
  call ddc#custom#patch_global('sourceParams', {
      \ 'buffer': {
      \     'cwdAsRoot': v:true,
      \ },
      \ })
  call ddc#custom#patch_filetype(['css', 'typescriptreact'], {
      \ 'sourceParams': {
      \   'vim-lsp': {
      \     'ignoreCompleteProvider': v:true,
      \   },
      \ },
      \ })
  call ddc#custom#patch_global('autoCompleteEvents', [
      \ 'InsertEnter', 'TextChangedI', 'TextChangedP',
      \ 'CmdlineEnter', 'CmdlineChanged', 'TextChangedT',
      \ ])
  call ddc#custom#patch_global('ui', 'pum')
  call pum#set_option({ 'use_complete': v:true })
  ""call popup_preview#enable()
  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
#repo = 'shun/ddc-vim-lsp'
#rev='v0.3.0-v1.20.0'
repo = '~/ghq/github.com/shun/ddc-vim-lsp'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-omni'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['ddc.vim']
on_source = 'ddc.vim'

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip-integ'
#depends = ['ddc.vim']
#on_source = 'ddc.vim'
#
#[[plugins]]
#repo = 'hrsh7th/vim-vsnip'
#depends = ['ddc.vim', 'vim-vsnip-integ']
#
