[[plugins]]
repo = 'Shougo/ddc.vim'
rev='v2.3.1'
depends = ['denops.vim']
on_event = 'InsertEnter'
hook_source = '''
  inoremap <silent><expr> <C-l> ddc#complete_common_string()
  inoremap <silent><expr> <CR>  pumvisible() ? "\<C-y>" : "\<CR>"
  call ddc#custom#patch_global('sources', ['vim-lsp', 'around', 'buffer', 'file'])
  call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'ignoreCase': v:true,
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \ },
      \ 'around': {
      \     'mark': 'A',
      \  },
      \ 'buffer': {
      \     'mark': 'B',
      \  },
      \ 'file': {
      \     'mark': 'F',
      \     'isVolatile': v:true,
      \     'forceCompletionPattern': '\S/\S*',
      \     'cwdAsRoot': v:true,
      \     'minAutoCompleteLength': 1,
      \  },
      \ 'vim-lsp': {
      \     'mark': 'LSP',
      \     'forceCompletionPattern': '\.\w*|:\w*|->\w*',
      \     'minAutoCompleteLength': 1,
      \ },
      \ })
  call ddc#custom#patch_global('sourceParams', {
      \ 'buffer': {
      \    'requireSameFiletype': v:false
      \ },
      \ })
  call ddc#custom#patch_filetype(['css', 'typescriptreact'], {
      \ 'sourceParams': {
      \   'vim-lsp': {
      \     'ignoreCompleteProvider': v:true,
      \   },
      \ },
      \ })
  call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
#repo = 'shun/ddc-vim-lsp'
#rev='v0.3.0-v1.20.0'
repo = '~/ghq/github.com/shun/ddc-vim-lsp'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-omni'
depends = ['ddc.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
depends = ['ddc.vim']
on_source = 'ddc.vim'

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip-integ'
#depends = ['ddc.vim']
#on_source = 'ddc.vim'
#
#[[plugins]]
#repo = 'hrsh7th/vim-vsnip'
#depends = ['ddc.vim', 'vim-vsnip-integ']
#
